import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Recipe App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <script src='https://kit.fontawesome.com/bafe0bdc31.js' crossorigin='anonymous'></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
